const { defineConfig } = require("cypress");

module.exports = defineConfig({
  reporter: "mochawesome",
  reporterOptions: {
    overwrite: true,
    html: true,
    json: false,
    inline: true,
    reportPageTitle: "Flo tests",
    reportTitle: "Flo tests",
    reportFilename: "[status]_[datetime]-report",
    timestamp: "dddd_mmmm_dS_yyyy-h_MM_ss_TT",
  },
  video: true,
  videoCompression: true,
  requestTimeout: 60000,
  defaultCommandTimeout: 60000,
  pageLoadTimeout: 120000,
  responseTimeout: 120000,
  viewportWidth: 1920,
  viewportHeight: 1080,
  chromeWebSecurity: false,
  numTestsKeptInMemory: 2,
  watchForFileChanges: false,
  experimentalMemoryManagement: true,
  trashAssetsBeforeRuns: true,
  retries: 2,
  blockHosts: [
    "cmp.osano.com",
    "a5641440198393856.cdn.optimizely.com",
    "securepubads.g.doubleclick.net",
    "www.recaptcha.net",
    "s.amazon-adsystem.com",
    "ads.pubmatic.com",
    "ad-cdn.technoratimedia.com",
    "ssum-sec.casalemedia.com",
    "ssp.api.tappx.com",
    "eb2.3lift.com",
    "sync.go.sonobi.com",
    "ap.lijit.com",
    "e1.emxdgt.com",
    "sync.inmobi.com",
    "ssbsync-us.smartadserver.com",
    "sync-amz.ads.yieldmo.com",
    "ib.adnxs.com",
    "bh.contextweb.com",
    "cs-tam.yellowblue.io",
    "u.openx.net",
    "amazon-tam-match.dotomi.com",
    "ce.lijit.com",
    "ms-cookie-sync.presage.io",
    "secure-assets.rubiconproject.com",
    "onetag-sys.com",
    "ssc-cms.33across.com",
    "ad.360yield.com",
    "ssbsync.smartadserver.com",
    "ssp.disqus.com",
    "ssp-sync.criteo.com",
    "eus.rubiconproject.com",
    "sync.adkernel.com",
    "de.tynt.com",
    "hde.tynt.com",
    "34e766ec158e03cd3aa3d19c4ba76ec3.safeframe.googlesyndication.com",
    "acdn.adnxs.com",
    "js-sec.indexww.com",
    "sdk.streamrail.com",
    "us-u.openx.net",
    "www.googleadservices.com",
    "rtb.gumgum.com",
    "c1.adform.net",
    "match.adsrvr.org",
    "creativecdn.com",
    "pbs-cs.yellowblue.io",
    "tg.socdm.com",
    "match.prod.bidr.io",
    "cm.g.doubleclick.net",
    "a.tribalfusion.com",
    "cms.quantserve.com",
    "p.rfihub.com",
    "beacon.lynx.cognitivlabs.com",
    "sync.srv.stackadapt.com",
    "sync-tm.everesttech.net",
    "s.tribalfusion.com",
    "rtb-csync.smartadserver.com",
    "simage2.pubmatic.com",
    "t.adx.opera.com",
    "x.bidswitch.net",
    "www.temu.com",
    "odr.mookie1.com",
    "global.ib-ibi.com",
    "cs.krushmedia.com",
    "cs.iqzone.com",
    "dis.criteo.com",
    "csync.loopme.me",
    "gocm.c.appier.net",
    "pm.w55c.net",
    "ib.mookie1.com",
    "sync.resetdigital.co",
    "sync.1rx.io",
    "um.simpli.fi",
    "ums.acuityplatform.com",
    "s.ntv.io",
    "postrelease.com",
    "sync.targeting.unrulymedia.com",
    "image8.pubmatic.com",
    "pixel.33across.com",
    "image4.pubmatic.com",
    "pagead2.googlesyndication.com",
    "pixel.rubiconproject.com",
    "ep2.adtrafficquality.google",
    "www.google.com",
    "flosports-d.openx.net",
    "prebid.a-mo.net",
    "contextual.media.net",
    "d.clarity.ms",
    "siop.flosports.tv",
    "c.amazon-adsystem.com",
    "app30.flosports.tv",
    "conduit.redfast.com",
    "**pdmp.tagger.opecloud.com**",
    "**logx.optimizely.com**",
    "**flosports.sjv.io**",
  ],
  e2e: {
    baseUrl: "https://www.flowrestling.org",
    scrollBehavior: "center",
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});
