name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npm run test:run:local

      # Upload Mochawesome report as artifact
      - name: Upload Mochawesome Report
        if: always() # ensures this runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report/
